apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:solar-system-app
  name: solar-system
  namespace: ${NAMESPACE}
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: solar-system-app
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system-app
    spec:
      containers:
      - image: ${K8S_IMAGE}
        imagePullPolicy: Always
        name: solar-system
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        envFrom:
        - secretRef:
            name: mongo-db-creds