apiVersion: v1
kind: Service
metadata:
  name: solar-system-app-service
  namespace: ${NAMESPACE}
  labels:                    
    app: solar-system-app    
spec:
  selector:
    app: solar-system-app 
  ports:
    - protocol: TCP
      port: 3000          
      targetPort: 3000  
  type: LoadBalancer 